const cardImage = {
  'Luke Skywalker': '../Utils/assets/cards/luke-skywalker.jpg',
  'C-3PO': '../Utils/assets/cards/c-3po.jpg',
  'R2-D2': '../Utils/assets/cards/r2-d2.jpg',
  'Darth Vader': '../Utils/assets/cards/darthvader.jpg',
  'Leia Organa': '../Utils/assets/cards/Leia.jpg',
  'Owen Lars': '../Utils/assets/cards/uncle.jpg',
  'Beru Whitesun lars': '../Utils/assets/cards/beru.jpg',
  'R5-D4': '../Utils/assets/cards/r5-d4.jpg',
  'Biggs Darklighter': '../Utils/assets/cards/biggs.jpg',
  'Obi-Wan Kenobi': '../Utils/assets/cards/obi-wan.jpg',
  'Alderaan': '../Utils/assets/cards/alderaan.jpg',
  'Yavin IV': '../Utils/assets/cards/yavin.jpg',
  'Hoth': '../Utils/assets/cards/hoth.jpg',
  'Dagobah': '../Utils/assets/cards/dagobah.jpg',
  'Bespin': '../Utils/assets/cards/bespin.jpg',
  'Endor': '../Utils/assets/cards/endor.jpg',
  'Naboo': '../Utils/assets/cards/noboo.jpg',
  'Coruscant': '../Utils/assets/cards/cruscant.jpg',
  'Kamino': '../Utils/assets/cards/kamino.jpg',
  'Geonosis': '../Utils/assets/cards/geonosis.jpg',
  'Sand Crawler': '../Utils/assets/cards/sand.jpg',
  'T-16 skyhopper': '../Utils/assets/cards/skyhopper.jpg',
  'X-34 landspeeder': '../Utils/assets/cards/landspeeder.jpg',
  'Snowspeeder': '../Utils/assets/cards/snowspeed.jpg',
  'TIE bomber': '../Utils/assets/cards/bomber.jpg',
  'AT-AT': '../Utils/assets/cards/at-at.jpg',
  'AT-ST': '../Utils/assets/cards/at-st.jpg',
  'Storm IV Twin-Pod cloud car': '../Utils/assets/cards/pod.jpg',
  'Sail barge': '../Utils/assets/cards/sail.jpg'
}