const cardImage = {
  'Luke Skywalker': require('../Utils/assets/cards/luke-skywalker.jpg'),
  'C-3PO': require('../Utils/assets/cards/c-3po.jpg'),
  'R2-D2': require('../Utils/assets/cards/r2-d2.jpg'),
  'Darth Vader': require('../Utils/assets/cards/darthvader.jpg'),
  'Leia Organa': require('../Utils/assets/cards/Leia.jpg'),
  'Owen Lars': require('../Utils/assets/cards/uncle.jpg'),
  'Beru Whitesun lars': require('../Utils/assets/cards/beru.jpg'),
  'R5-D4': require('../Utils/assets/cards/r5-d4.jpg'),
  'Biggs Darklighter': require('../Utils/assets/cards/biggs.jpg'),
  'Obi-Wan Kenobi': require('../Utils/assets/cards/obi-wan.jpg'),
  'Alderaan': require('../Utils/assets/cards/alderaan.jpg'),
  'Yavin IV': require('../Utils/assets/cards/yavin.jpg'),
  'Hoth': require('../Utils/assets/cards/hoth.jpg'),
  'Dagobah': require('../Utils/assets/cards/dagobah.jpg'),
  'Bespin': require('../Utils/assets/cards/bespin.jpg'),
  'Endor': require('../Utils/assets/cards/endor.jpg'),
  'Naboo': require('../Utils/assets/cards/noboo.jpg'),
  'Coruscant': require('../Utils/assets/cards/cruscant.jpg'),
  'Kamino': require('../Utils/assets/cards/kamino.jpg'),
  'Geonosis': require('../Utils/assets/cards/geonosis.jpg'),
  'Sand Crawler': require('../Utils/assets/cards/sand.jpg'),
  'T-16 skyhopper': require('../Utils/assets/cards/skyhopper.jpg'),
  'X-34 landspeeder': require('../Utils/assets/cards/landspeeder.jpg'),
  'TIE/LN starfighter': require('../Utils/assets/cards/tie.jpg'),
  'Snowspeeder': require('../Utils/assets/cards/snowspeed.jpg'),
  'TIE bomber': require('../Utils/assets/cards/bomber.jpg'),
  'AT-AT': require('../Utils/assets/cards/at-at.jpg'),
  'AT-ST': require('../Utils/assets/cards/at-st.jpg'),
  'Storm IV Twin-Pod cloud car': require('../Utils/assets/cards/pod.jpg'),
  'Sail barge': require('../Utils/assets/cards/sail.jpg'),
  true: require('../Utils/assets/cards/star-true.svg'),
  false: require('../Utils/assets/cards/star-false.svg')
}

export default cardImage;